export const COLOR_BG = '#2a2a2a'
export const COLOR_DEFAULT_STROKE = '#030303'
export const COLOR_DRAG_STROKE = 'yellow'
export const COLOR_NODE_FILL = '#3a3a3a'
export const COLOR_SELECTED_STROKE = 'aqua'
export const COLOR_TEXT = '#aaa'
